server:
  port: 8888

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    show-sql: false
  datasource:
    url: jdbc:mysql://moodtracker.h1n.ru:3306/mood_tracker_db
    username: admin
    password: O!GZuXf34&xP
    driver-class-name: com.mysql.cj.jdbc.Driver